# Generated by Django 3.0.2 on 2020-02-14 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('heading0', models.CharField(max_length=140)),
                ('post0', models.TextField()),
                ('heading1', models.CharField(max_length=140)),
                ('post1', models.TextField()),
                ('pub_date', models.DateField()),
                ('file_name', models.FileField(default=0, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=0, max_length=20)),
                ('msg', models.TextField()),
                ('com_date', models.DateTimeField(default=datetime.datetime.now)),
                ('approved', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.News')),
            ],
        ),
    ]
