# Generated by Django 3.0.2 on 2020-02-15 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=120)),
                ('Password', models.CharField(default=0, max_length=15)),
                ('Re_Password', models.CharField(default=0, max_length=15)),
                ('Phone', models.IntegerField()),
                ('com_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
