# Generated by Django 3.0.2 on 2020-02-19 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mess_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('mes_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
